import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://jngowzpawtwhwzyzckwe.supabase.co'
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuZ293enBhd3R3aHd6eXpja3dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTQxMDAsImV4cCI6MjA3MDMzMDEwMH0.FIQEMJsMa632x0GRUO4sSNJO3tq8M3e5bWH5JzUXpVc'

export const supabase = createClient(supabaseUrl, supabaseAnonKey)

const supabaseServiceKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuZ293enBhd3R3aHd6eXpja3dlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NDc1NDEwMCwiZXhwIjoyMDcwMzMwMTAwfQ.Knbg0I8g3sqJVWHLGj3rIUnS7EXoUSiY5xUsKcs0E2A'

export const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey)
